server:
  port: 8000

spring:
  application:
    name: apigateway-service

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  swagger-ui:
    urls[0]:
      name: user-service
      url: /user-service/v3/api-docs
    urls[1]:
      name: product-service
      url: /product-service/v3/api-docs
    urls[2]:
      name: order-service
      url: /order-service/v3/api-docs
    urls[3]:
      name: notification-service
      url: /notification-service/v3/api-docs
    urls[4]:
      name: board-service
      url: /board-service/v3/api-docs
    urls[5]:
      name: basket-service
      url: /basket-service/v3/api-docs
    use-root-path: true

management:
  endpoints:
    web:
      exposure:
        include: "*"